export const appPaths = {
  home: "/",
  login: "/login",
  signUp: "/sign-up",
  forgotPassword: "/forgot-password",
  dashboard: "/app",
  searches: "/app/searches",
  leads: "/app/leads",
  aiAnalysis: "/app/ai-analysis",
  assistant: "/app/assistant",
  outreach: "/app/outreach",
  campaigns: "/app/campaigns",
  crm: "/app/crm",
  admin: "/app/admin",
  workspaceAdmin: "/app/workspace-admin",
  adminWorkspaces: "/app/admin/workspaces",
  adminWorkspaceDetail: (workspaceId: string) =>
    `/app/admin/workspaces/${workspaceId}`,
  adminUsers: "/app/admin/users",
  adminBilling: "/app/admin/billing",
  adminUsage: "/app/admin/usage",
  adminProviders: "/app/admin/providers",
  adminJobs: "/app/admin/jobs",
  adminAi: "/app/admin/ai",
  auditLogs: "/app/audit-logs",
  exports: "/app/exports",
  settings: "/app/settings",
  team: "/app/team",
  billing: "/app/billing",
  invoices: "/app/invoices",
  usage: "/app/usage",
  leadDetail: (leadId: string) => `/app/leads/${leadId}`,
  campaignDetail: (campaignId: string) => `/app/campaigns/${campaignId}`,
  dealDetail: (dealId: string) => `/app/crm/deals/${dealId}`,
  searchJobDetail: (jobId: string) => `/app/searches/jobs/${jobId}`,
} as const;
